name: Build And Push to ECR

on:
    push:
        # pull_requests:
        #    branches: ['main' , 'dev']
        branches: [ 'main']

jobs:
    build_scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Code
              uses: actions/checkout@v7
            - name: Trivy Scan
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                scan-type: 'fs'
                severity: HIGH,CRITICAL
                exit-code: 1
            - name: Build Docker Image
              run: docker build -t 741010684914.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .
            - name: Scan image with Trivy
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: 741010684914.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
                format: table  
                exit-code: 1
                ignore-unfixed: true
                severity: CRITICAL,HIGH
            - name: Push image to Ecr
              run: echo "push"